tap 'homebrew/services'

tap 'drone/drone'
tap 'heroku/brew'
tap 'nodenv/nodenv'
tap 'thoughtbot/formulae'

# Build tools and libs
brew 'coreutils'
brew 'gmp'
brew 'libyaml'
brew 'makedepend'
brew 'pkg-config'
brew 'readline'

brew 'antigen'
brew 'awscli'
brew 'bitrise'
brew 'git'
brew 'diff-so-fancy'
brew 'goenv'
brew 'heroku/brew/heroku'
brew 'imagemagick'
brew 'ios-deploy'
brew 'node-build'
brew 'nodenv-aliases'
brew 'nodenv-vars'
brew 'nodenv'
brew 'openssl'
brew 'pyenv'
brew 'thoughtbot/formulae/parity'
brew 'rbenv-aliases'
brew 'rbenv-default-gems'
brew 'rbenv-vars'
brew 'rbenv'
brew 'ruby-build'
brew 'tldr'
brew 'yarn'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'zsh'


brew 'postgresql', start_service: false
brew 'mysql', start_service: false
brew 'redis', start_service: false

cask 'docker'
cask 'iterm2'
cask 'postman'
cask 'slack'
cask 'telegram'
cask 'visual-studio-code'
cask 'vlc'
cask 'firefox'
cask 'tor-browser'
cask 'transmission'
